{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ivangeevo.btwr",
    "module": "BTWRemastered-private",
    "version": "0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BTWRemastered-private-0.21.jar",
          "url": "BTWRemastered-private-0.21.jar",
          "size": 4402908,
          "sha512": "27fa3d510fcae0f9763646150ae3ac546d40613819a11583dc2f0b5ae66eddeae19bac6e51c9281d99df7478a73322a6fde4c6b7876bd5ab1b0dd142d11a2239",
          "sha256": "e3084395eef6779131f3f870cdf938859aa683d0d6b172047f233cdf9ba34cda",
          "sha1": "8c8125d5ed7734d1b99ca5283d9a6ce45365d4a0",
          "md5": "a66a7982aad66682d01ef500a6dd3853"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "BTWRemastered-private-0.21.jar",
          "url": "BTWRemastered-private-0.21.jar",
          "size": 4402908,
          "sha512": "27fa3d510fcae0f9763646150ae3ac546d40613819a11583dc2f0b5ae66eddeae19bac6e51c9281d99df7478a73322a6fde4c6b7876bd5ab1b0dd142d11a2239",
          "sha256": "e3084395eef6779131f3f870cdf938859aa683d0d6b172047f233cdf9ba34cda",
          "sha1": "8c8125d5ed7734d1b99ca5283d9a6ce45365d4a0",
          "md5": "a66a7982aad66682d01ef500a6dd3853"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BTWRemastered-private-0.21-sources.jar",
          "url": "BTWRemastered-private-0.21-sources.jar",
          "size": 4361325,
          "sha512": "4b842ce3e61d5e060792387c4e12fca7534718f1c1a9126e7497f51fd1ddb51bdef17ff32acd145c11b5dc2d2f65cdc0b65fc14a6ea4e7008081a76736f9222a",
          "sha256": "39d5c7964804f68c1aa65d4e7606603a62acc95f18f7c2267e14911bcfbb2632",
          "sha1": "e2b4bd4fe0599faa09f7d84be15622d3bc24a8aa",
          "md5": "83d3c640ee1dfe0a02745bb97ee4809e"
        }
      ]
    }
  ]
}
